/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Procesos;



import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhoan
 */
public class GenerarCobro extends javax.swing.JFrame {
    Boolean crear = false;
   public static String Satigualinea="";

    /**
     * Creates new form GenerarCobro
     */
    public GenerarCobro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ID_Cobro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Fecha_Cobro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ID_Cliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Valor_Cobro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Concepto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Status_Cobro = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Nombre_cliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 488));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/procesamiento-por-lotes.png"))); // NOI18N
        jLabel1.setText("Generar Cobro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("ID Cobro");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        ID_Cobro.setBackground(new java.awt.Color(204, 204, 204));
        ID_Cobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_CobroActionPerformed(evt);
            }
        });
        jPanel1.add(ID_Cobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 340, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Fecha");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        Fecha_Cobro.setBackground(new java.awt.Color(204, 204, 204));
        Fecha_Cobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fecha_CobroActionPerformed(evt);
            }
        });
        jPanel1.add(Fecha_Cobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 340, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("ID Cliente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        ID_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        ID_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(ID_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 340, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Valor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        Valor_Cobro.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Valor_Cobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 340, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Concepto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        Concepto.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 340, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Status");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        Status_Cobro.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Status_Cobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 340, -1));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, -1, 30));
        jPanel1.add(Nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 180, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ID_CobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_CobroActionPerformed
        // TODO add your handling code here:
        int cod;
        boolean encontrado=false;

        cod=Integer.parseInt(ID_Cobro.getText());

        Scanner s;

        try {
            File f=new File("C:archivoCobro1.txt");
            s = new Scanner(f);
            if(!f.exists())
            {
                f.createNewFile();
            }
            else
            {
                while (s.hasNextLine() && !encontrado)
                {
                    String linea = s.nextLine();

                    Scanner sl = new Scanner(linea);

                    sl.useDelimiter("\\s*;\\s*");
                    Fecha_Cobro.setText(fechaActual());
                    try {
                        if(cod==Integer.parseInt(sl.next()))
                        {
                            Fecha_Cobro.setText(sl.next());
                            ID_Cliente.setText(sl.next());
                            Valor_Cobro.setText(sl.next());
                            Concepto.setText(sl.next());
                            Status_Cobro.setText(sl.next());

                            encontrado=true;
                            crear = true;
                            Satigualinea=(ID_Cobro.getText() + ";" +Fecha_Cobro.getText()
                            + ";" +ID_Cliente.getText()+ ";" + Valor_Cobro.getText()+ ";" 
                            + Concepto.getText()+ ";" + Status_Cobro.getText());

                        }
                        else
                        {  //Salida.setText("Este registro no existe");
                            Fecha_Cobro.setText(fechaActual());
                            ID_Cliente.setText("");
                            Valor_Cobro.setText("");
                            Concepto.setText("");
                            Status_Cobro.setText("");

                            encontrado=false;
                            crear = false;

                        }
                    } // fin try
                    catch (Exception  e1)
                    {
                        // JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e1);

                    }
                } // fin while
            }

            s.close();
        } // fin try
        catch (FileNotFoundException e1)

        {
            JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e1);
            //e1.printStackTrace();
        }
        catch (IOException e1)
        {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
    }//GEN-LAST:event_ID_CobroActionPerformed

    private void Fecha_CobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fecha_CobroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fecha_CobroActionPerformed

    private void ID_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_ClienteActionPerformed
        // TODO add your handling code here:
        int cod;
        boolean encontrado=false;
 
        cod=Integer.parseInt(ID_Cliente.getText());
 
        Scanner s;
 
        try {
            File f = new File("C:archivoCliente1.txt");
            s= new Scanner(f);
            if(!f.exists())
            {
                f.createNewFile();
            }
            else
            {
                while (s.hasNextLine() && !encontrado)
                {
                    String linea = s.nextLine();
                    Scanner sl = new Scanner(linea);
 
                    sl.useDelimiter("\\s*;\\s*");
 
                    try {
                        if(cod==Integer.parseInt(sl.next()))
                        {
                            Nombre_cliente.setText(sl.next());
                            encontrado=true;
                        }
                    } // fin try
                    catch (NumberFormatException e1)
                    {
                        JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e1);
                    }
                } // fin while
                if(encontrado==false){
                    JOptionPane.showMessageDialog(this, "Error, ID Localizacion no existe en el archivo ");
                    Nombre_cliente.setText("");
                }
            }
            s.close();
        } // fin try
        catch (FileNotFoundException e1)
        {
            JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e1);
            e1.printStackTrace();
        }
        catch (IOException e1)
        {
            // TODO Auto-generated catch block
        }
    }//GEN-LAST:event_ID_ClienteActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        String id_cobro="";
        String fecha="";
        String id_cliente="";
        String valor="";
        String concepto="";
        String status="";
        String Snuevalinea="";

        ManejoArchivoCobro MAC=new ManejoArchivoCobro();
        id_cobro=ID_Cobro.getText();
        fecha=Fecha_Cobro.getText();
        id_cliente=ID_Cliente.getText();
        valor=Valor_Cobro.getText();
        concepto=Concepto.getText();
        status=Status_Cobro.getText();
        

        try {

            if (crear==false)
            {
                MAC.GuardarDatos (id_cobro,fecha,id_cliente
               ,valor,concepto,status);
            }
            else
            {
                Snuevalinea=(id_cobro + ";" + fecha + ";" + id_cliente + ";" 
                + valor+ concepto + ";" + status);
                MAC.ModificaDatos(Satigualinea,Snuevalinea,id_cobro);
            }
            ID_Cobro.setText("");
            Fecha_Cobro.setText("");
            ID_Cliente.setText("");
            Valor_Cobro.setText("");
            Concepto.setText("");
            Status_Cobro.setText("");
            Nombre_cliente.setText("");
            //Salida.setText("");
        } // fin try
        catch (IOException e1)
        {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_GuardarActionPerformed

    public static String fechaActual(){
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        
        return formatoFecha.format(fecha);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarCobro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Concepto;
    private javax.swing.JTextField Fecha_Cobro;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField ID_Cliente;
    private javax.swing.JTextField ID_Cobro;
    private javax.swing.JLabel Nombre_cliente;
    private javax.swing.JTextField Status_Cobro;
    private javax.swing.JTextField Valor_Cobro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
