/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Procesos;

import java.awt.Color;

/**
 *
 * @author Jhoan
 */
public class GenerarCobro extends javax.swing.JFrame {

boolean encontrado=false;
boolean crear =false;
double valor;
double bala,bl;
double b=0;
int num;
int n;
    /**
     * Creates new form GenerarCobro
     */
    public GenerarCobro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Status = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ID_Cobro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Fecha_Cobro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ID_Cliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Valor_Cobro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Concepto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Status_Cobro = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Nombre_cliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 488));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/procesamiento-por-lotes.png"))); // NOI18N
        jLabel1.setText("Generar Cobro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Comprobador");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, -1, -1));

        Status.setBackground(new java.awt.Color(204, 204, 204));
        Status.setEnabled(false);
        jPanel1.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 150, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("ID Cobro");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        ID_Cobro.setBackground(new java.awt.Color(204, 204, 204));
        ID_Cobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_CobroActionPerformed(evt);
            }
        });
        jPanel1.add(ID_Cobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 170, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Fecha");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        Fecha_Cobro.setBackground(new java.awt.Color(204, 204, 204));
        Fecha_Cobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fecha_CobroActionPerformed(evt);
            }
        });
        jPanel1.add(Fecha_Cobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 170, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("ID Cliente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        ID_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        ID_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(ID_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 170, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Valor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        Valor_Cobro.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Valor_Cobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 170, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Concepto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        Concepto.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 170, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Status");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        Status_Cobro.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Status_Cobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 170, -1));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, 30));
        jPanel1.add(Nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 180, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ID_CobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_CobroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ID_CobroActionPerformed

    private void Fecha_CobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fecha_CobroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fecha_CobroActionPerformed

    private void ID_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_ClienteActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarCobro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Concepto;
    private javax.swing.JTextField Fecha_Cobro;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField ID_Cliente;
    private javax.swing.JTextField ID_Cobro;
    private javax.swing.JLabel Nombre_cliente;
    private javax.swing.JTextField Status;
    private javax.swing.JTextField Status_Cobro;
    private javax.swing.JTextField Valor_Cobro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
