/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reservas;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhoan
 */
public class Reserva extends javax.swing.JFrame {

    /**
     * Creates new form Reserva
     */
    public Reserva() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    Boolean crear = false;
   public static String Satigualinea="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID_Reserva = new javax.swing.JTextField();
        Status = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ID_Sala = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ID_Cliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Fecha_Reserva = new javax.swing.JTextField();
        ID_Horario_Reserva = new javax.swing.JTextField();
        ID_Estado_Reserva = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setMinimumSize(new java.awt.Dimension(790, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 488));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mantenimiento-web.png"))); // NOI18N
        jLabel1.setText("Reserva");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("ID Reserva");
        jLabel2.setPreferredSize(new java.awt.Dimension(91, 17));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 80, -1));

        ID_Reserva.setBackground(new java.awt.Color(204, 204, 204));
        ID_Reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_ReservaActionPerformed(evt);
            }
        });
        jPanel1.add(ID_Reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 190, -1));

        Status.setBackground(new java.awt.Color(204, 204, 204));
        Status.setEnabled(false);
        jPanel1.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 170, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Comprobador");
        jLabel3.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel3.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 90, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("ID Sala");
        jLabel4.setPreferredSize(new java.awt.Dimension(91, 17));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 50, -1));

        ID_Sala.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(ID_Sala, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 190, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("ID Cliente");
        jLabel5.setPreferredSize(new java.awt.Dimension(91, 17));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 70, -1));

        ID_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(ID_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 190, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Fecha");
        jLabel6.setPreferredSize(new java.awt.Dimension(91, 17));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 40, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("ID Horario/Reserva");
        jLabel7.setPreferredSize(new java.awt.Dimension(91, 17));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 130, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("ID Estado/Reserva");
        jLabel8.setPreferredSize(new java.awt.Dimension(91, 17));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 120, -1));

        Fecha_Reserva.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Fecha_Reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 190, -1));

        ID_Horario_Reserva.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(ID_Horario_Reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 190, -1));

        ID_Estado_Reserva.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(ID_Estado_Reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 190, -1));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, 30));

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ID_ReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_ReservaActionPerformed
        // TODO add your handling code here:
        int cod;
        boolean encontrado=false;

        cod=Integer.parseInt(ID_Reserva.getText());

        Scanner s;

        try {
            File f=new File("C:archivoReserva1.txt");
            s = new Scanner(f);
            if(!f.exists())
            {
                f.createNewFile();
            }
            else
            {
                while (s.hasNextLine() && !encontrado)
                {
                    String linea = s.nextLine();

                    Scanner sl = new Scanner(linea);

                    sl.useDelimiter("\\s*;\\s*");
                    try {
                        if(cod==Integer.parseInt(sl.next()))
                        {
                            ID_Sala.setText(sl.next());
                            ID_Cliente.setText(sl.next());
                            Fecha_Reserva.setText(sl.next());
                            ID_Horario_Reserva.setText(sl.next());
                            ID_Estado_Reserva.setText(sl.next());

                            encontrado=true;
                            crear = true;
                            Satigualinea=(ID_Reserva.getText() + ";" +ID_Sala.getText()+ ";" + ID_Cliente.getText() + ";" + Fecha_Reserva.getText() 
                            +";"+ID_Horario_Reserva.getText()+ ";" +ID_Estado_Reserva.getText());
                            Status.setText("Modificando");
                        }
                        else
                        {  //Salida.setText("Este registro no existe");
                            ID_Sala.setText("");
                            ID_Cliente.setText("");
                            Fecha_Reserva.setText("");
                            ID_Horario_Reserva.setText("");
                            ID_Estado_Reserva.setText("");

                            encontrado=false;
                            crear = false;
                            Status.setText("Creando");
                        }
                    } // fin try
                    catch (Exception  e1)
                    {
                       // JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e1);
                       
                    }
                } // fin while
            }

            s.close();
        } // fin try
        catch (FileNotFoundException e1)

        {
            JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e1);
            //e1.printStackTrace();
        }
        catch (IOException e1)
        {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
        
    }//GEN-LAST:event_ID_ReservaActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        ID_Reserva.setText("");
        ID_Sala.setText("");
        ID_Cliente.setText("");
        Fecha_Reserva.setText("");
        ID_Horario_Reserva.setText("");
        ID_Estado_Reserva.setText("");
        Status.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        String id_reserva="";
        String id_sala="";
        String id_cliente="";
        String fecha_reserva="";
        String id_horario_reserva="";
        String id_estado_reserva="";
        String Snuevalinea="";

        ManejoArchivoReserva MAR=new ManejoArchivoReserva();
        id_reserva=ID_Reserva.getText();
        id_sala=ID_Sala.getText();
        id_cliente=ID_Cliente.getText();
        fecha_reserva=Fecha_Reserva.getText();
        id_horario_reserva=ID_Horario_Reserva.getText();
        id_estado_reserva=ID_Estado_Reserva.getText();
        

        try {

            if (crear==false)
            {
                MAR.GuardarDatos (id_reserva,id_sala,id_cliente,fecha_reserva
                ,id_horario_reserva,id_estado_reserva);
            }
            else
            {
                Snuevalinea=(id_reserva + ";" + id_sala + ";" + id_cliente + ";" + fecha_reserva
                + ";" + id_horario_reserva + ";" + id_estado_reserva);
                MAR.ModificaDatos(Satigualinea,Snuevalinea,id_reserva);
            }
            ID_Reserva.setText("");
            ID_Sala.setText("");
            ID_Cliente.setText("");
            Fecha_Reserva.setText("");
            ID_Horario_Reserva.setText("");
            ID_Estado_Reserva.setText("");
            Status.setText("");
            //Salida.setText("");
        } // fin try
        catch (IOException e1)
        {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Fecha_Reserva;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField ID_Cliente;
    private javax.swing.JTextField ID_Estado_Reserva;
    private javax.swing.JTextField ID_Horario_Reserva;
    private javax.swing.JTextField ID_Reserva;
    private javax.swing.JTextField ID_Sala;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextField Status;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
