/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Cliente;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhoan
 */
public class Cliente extends javax.swing.JFrame {

    /** Creates new form Cliente */
    public Cliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    Boolean crear = false;
   public static String Satigualinea="";

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID_Cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Status = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nombre_Cliente = new javax.swing.JTextField();
        Apellido_P = new javax.swing.JTextField();
        Apellido_M = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Direccion_Cliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Celular_Cliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Telefono_Cliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Fecha_Nacimiento_Cliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Fecha_Ingreso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Status_Cliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Tipo_Cliente = new javax.swing.JTextField();
        Correo_Cliente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Balance_Cliente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Valor_Cuota_Cliente = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setMinimumSize(new java.awt.Dimension(790, 330));
        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 488));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mantenimiento-web.png"))); // NOI18N
        jLabel1.setText("Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("ID Cliente");
        jLabel2.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 70, 20));

        ID_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        ID_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(ID_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 180, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Comprobador");
        jLabel3.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel3.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 90, 20));

        Status.setBackground(new java.awt.Color(204, 204, 204));
        Status.setEnabled(false);
        jPanel1.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 170, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Nombre");
        jLabel4.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel4.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 50, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Apellido Padre");
        jLabel5.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel5.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 90, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Apellido Madre");
        jLabel6.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel6.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, 20));

        Nombre_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Nombre_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 180, -1));

        Apellido_P.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Apellido_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 180, -1));

        Apellido_M.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Apellido_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 180, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Direccion ");
        jLabel7.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel7.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 70, 20));

        Direccion_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Direccion_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 260, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Fecha/Nacimiento");
        jLabel8.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel8.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 110, 20));

        Celular_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Celular_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 260, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Telefono/Casa");
        jLabel9.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel9.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 90, 20));

        Telefono_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Telefono_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 260, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Celular");
        jLabel10.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel10.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 50, 20));

        Fecha_Nacimiento_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Fecha_Nacimiento_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 260, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Fecha/Ingreso");
        jLabel11.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel11.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 90, 20));

        Fecha_Ingreso.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Fecha_Ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 180, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Status");
        jLabel12.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel12.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 40, 20));

        Status_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Status_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 180, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Tipo");
        jLabel13.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel13.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, 20));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Correo");
        jLabel14.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel14.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, 20));

        Tipo_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Tipo_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 180, -1));

        Correo_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Correo_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 260, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Balance");
        jLabel15.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel15.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, 20));

        Balance_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Balance_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 260, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Valor/Cuota");
        jLabel16.setMaximumSize(new java.awt.Dimension(95, 17));
        jLabel16.setMinimumSize(new java.awt.Dimension(95, 17));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, 20));

        Valor_Cuota_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Valor_Cuota_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 260, -1));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, -1, 30));

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ID_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_ClienteActionPerformed
        // TODO add your handling code here:
        int cod;
        boolean encontrado=false;

        cod=Integer.parseInt(ID_Cliente.getText());

        Scanner s;

        try {
            File f=new File("C:archivoCliente1.txt");
            s = new Scanner(f);
            if(!f.exists())
            {
                f.createNewFile();
            }
            else
            {
                while (s.hasNextLine() && !encontrado)
                {
                    String linea = s.nextLine();

                    Scanner sl = new Scanner(linea);

                    sl.useDelimiter("\\s*;\\s*");
                    try {
                        if(cod==Integer.parseInt(sl.next()))
                        {
                            Nombre_Cliente.setText(sl.next());
                            Apellido_P.setText(sl.next());
                            Apellido_M.setText(sl.next());
                            Direccion_Cliente.setText(sl.next());
                            Celular_Cliente.setText(sl.next());
                            Telefono_Cliente.setText(sl.next());
                            Fecha_Nacimiento_Cliente.setText(sl.next());
                            Fecha_Ingreso.setText(sl.next());
                            Status_Cliente.setText(sl.next());
                            Tipo_Cliente.setText(sl.next());
                            Correo_Cliente.setText(sl.next());
                            Balance_Cliente.setText(sl.next());
                            Valor_Cuota_Cliente.setText(sl.next());
                            encontrado=true;
                            crear = true;
                            Satigualinea=(ID_Cliente.getText() + ";" +Nombre_Cliente.getText()+ ";" +Apellido_P.getText()
                            + ";" + Apellido_M.getText()+ ";" +Direccion_Cliente.getText()+ ";" + Celular_Cliente.getText()
                            + ";" + Telefono_Cliente.getText()+ ";" + Fecha_Nacimiento_Cliente.getText()+ ";" + Fecha_Ingreso.getText()
                            + ";" + Status_Cliente.getText()+ ";" + Tipo_Cliente.getText()+ ";" + Correo_Cliente.getText()
                            + ";" + Balance_Cliente.getText()+ ";" + Valor_Cuota_Cliente.getText());
                            Status.setText("Modificando");
                        }
                        else
                        {  //Salida.setText("Este registro no existe");
                            Nombre_Cliente.setText("");
                            Apellido_P.setText("");
                            Apellido_M.setText("");
                            Direccion_Cliente.setText("");
                            Celular_Cliente.setText("");
                            Telefono_Cliente.setText("");
                            Fecha_Nacimiento_Cliente.setText("");
                            Fecha_Ingreso.setText("");
                            Status_Cliente.setText("");
                            Tipo_Cliente.setText("");
                            Correo_Cliente.setText("");
                            Balance_Cliente.setText("");
                            Valor_Cuota_Cliente.setText("");
                            encontrado=false;
                            crear = false;
                            Status.setText("Creando");
                        }
                    } // fin try
                    catch (Exception  e1)
                    {
                       // JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e1);
                       
                    }
                } // fin while
            }

            s.close();
        } // fin try
        catch (FileNotFoundException e1)

        {
            JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e1);
            //e1.printStackTrace();
        }
        catch (IOException e1)
        {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
    }//GEN-LAST:event_ID_ClienteActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        String id_cliente="";
        String nombre_cliente="";
        String apellido_p="";
        String apellido_m="";
        String direccion="";
        String celular="";
        String telefono="";
        String fecha_n="";
        String fecha_ingreso="";
        String status_c="";
        String tipo_c="";
        String correo="";
        String balance="";
        String valor_cuota="";
        
       
        String Snuevalinea="";

        ManejoArchivoCliente MAC=new ManejoArchivoCliente();
        id_cliente=ID_Cliente.getText();
        nombre_cliente=Nombre_Cliente.getText();
        apellido_p=Apellido_P.getText();
        apellido_m=Apellido_M.getText();
        direccion=Direccion_Cliente.getText();
        celular=Celular_Cliente.getText();
        telefono=Telefono_Cliente.getText();
        fecha_n=Fecha_Nacimiento_Cliente.getText();
        fecha_ingreso=Fecha_Ingreso.getText();
        status_c=Status_Cliente.getText();
        tipo_c=Tipo_Cliente.getText();
        
        if(Correo_Cliente.getText().isEmpty()){
           correo="--"; 
        }
        else{
        correo=Correo_Cliente.getText();
         }
        if(Balance_Cliente.getText().isEmpty()){
           balance="--"; 
        }
        else{
        balance=Balance_Cliente.getText();
         }
        if(Valor_Cuota_Cliente.getText().isEmpty()){
           valor_cuota="--"; 
        }
        else{
        valor_cuota=Valor_Cuota_Cliente.getText();
         }

        try {

            if (crear==false)
            {
                MAC.GuardarDatos (id_cliente,nombre_cliente,apellido_p,
                apellido_m,direccion,celular,telefono,fecha_n,
                fecha_ingreso,status_c,tipo_c,correo,balance,valor_cuota);
            }
            else
            {
                Snuevalinea=(id_cliente + ";" + nombre_cliente + ";" + apellido_p + ";" + apellido_m 
                + ";" + direccion + ";" + celular + ";" + telefono + ";" + fecha_n + ";" +fecha_ingreso
                + ";" + status_c + ";" + tipo_c + ";" + correo + ";" + balance + ";" +valor_cuota);
                MAC.ModificaDatos(Satigualinea,Snuevalinea, id_cliente);
            }
            ID_Cliente.setText("");
            Nombre_Cliente.setText("");
            Apellido_P.setText("");
            Apellido_M.setText("");
            Direccion_Cliente.setText("");
            Celular_Cliente.setText("");
            Telefono_Cliente.setText("");
            Fecha_Nacimiento_Cliente.setText("");
            Fecha_Ingreso.setText("");
            Status_Cliente.setText("");
            Tipo_Cliente.setText("");
            Correo_Cliente.setText("");
            Balance_Cliente.setText("");
            Valor_Cuota_Cliente.setText("");
            Status.setText("");
            //Salida.setText("");
        } // fin try
        catch (IOException e1)
        {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        ID_Cliente.setText("");
        Nombre_Cliente.setText("");
        Apellido_P.setText("");
        Apellido_M.setText("");
        Direccion_Cliente.setText("");
        Celular_Cliente.setText("");
        Telefono_Cliente.setText("");
        Fecha_Nacimiento_Cliente.setText("");
        Fecha_Ingreso.setText("");
        Status_Cliente.setText("");
        Tipo_Cliente.setText("");
        Correo_Cliente.setText("");
        Balance_Cliente.setText("");
        Valor_Cuota_Cliente.setText("");
        Status.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido_M;
    private javax.swing.JTextField Apellido_P;
    private javax.swing.JTextField Balance_Cliente;
    private javax.swing.JTextField Celular_Cliente;
    private javax.swing.JTextField Correo_Cliente;
    private javax.swing.JTextField Direccion_Cliente;
    private javax.swing.JTextField Fecha_Ingreso;
    private javax.swing.JTextField Fecha_Nacimiento_Cliente;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField ID_Cliente;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextField Nombre_Cliente;
    private javax.swing.JTextField Status;
    private javax.swing.JTextField Status_Cliente;
    private javax.swing.JTextField Telefono_Cliente;
    private javax.swing.JTextField Tipo_Cliente;
    private javax.swing.JTextField Valor_Cuota_Cliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
