/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Cliente.Cliente;
import Actividades.Actividades;
import Actividades.Consulta_Actividades;
import Cliente.Consulta_de_cliente;
import Cuota.Cuota;
import Entrenador.Entrenador;
import Ventanas.InicioSesion;
import Usuario.Usuario;
import EstadoReserva.EstadoReserva;
import HorarioActividades.Consulta_Horario_Actividades;
import HorarioActividades.HorarioActividades;
import Localizacion.Localizacion;
import Procesos.ActualizarCuota;
import Procesos.GenerarCobro;
import Procesos.ReversarCobro;
import Reservas.Reserva;
import ReservaActividades.ReservaActividades;
import Salas.Consulta_Salas;
import Salas.Salas;
import Usuario.Consulta_Usuario;
import Usuario.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author jerem
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_MUsuario = new javax.swing.JMenuItem();
        MEntrenador = new javax.swing.JMenuItem();
        MLocalizacion = new javax.swing.JMenuItem();
        MSalas = new javax.swing.JMenuItem();
        jMenuItem_MActividades = new javax.swing.JMenuItem();
        jMenuItem_MHorarioActividades = new javax.swing.JMenuItem();
        jMenuItem_MClientes = new javax.swing.JMenuItem();
        jMenuItem_MEstadoReservas = new javax.swing.JMenuItem();
        jMenuItem_MReservas = new javax.swing.JMenuItem();
        jMenuItem_MReversaActividades = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        CUsuario = new javax.swing.JMenuItem();
        CEntrenador = new javax.swing.JMenuItem();
        CLocalizacion = new javax.swing.JMenuItem();
        CSalas = new javax.swing.JMenuItem();
        CActividades = new javax.swing.JMenuItem();
        CHorarioActividaes = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        CClientes = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo de Bienvenida.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 640));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo de Bienvenida.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, -1, 40, 640));

        jMenu1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mantenimiento-web.png"))); // NOI18N
        jMenu1.setText("Mantenimientos");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        jMenuItem_MUsuario.setText("De Usuario");
        jMenuItem_MUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_MUsuario);

        MEntrenador.setText("De Entrenador");
        MEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEntrenadorActionPerformed(evt);
            }
        });
        jMenu1.add(MEntrenador);

        MLocalizacion.setText("De Localizacion");
        MLocalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLocalizacionActionPerformed(evt);
            }
        });
        jMenu1.add(MLocalizacion);

        MSalas.setText("De Salas");
        MSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSalasActionPerformed(evt);
            }
        });
        jMenu1.add(MSalas);

        jMenuItem_MActividades.setText("De Actividades");
        jMenuItem_MActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MActividadesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_MActividades);

        jMenuItem_MHorarioActividades.setText("De Horarios Actividades");
        jMenuItem_MHorarioActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MHorarioActividadesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_MHorarioActividades);

        jMenuItem_MClientes.setText("Clientes");
        jMenuItem_MClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_MClientes);

        jMenuItem_MEstadoReservas.setText("Estado Reservas");
        jMenuItem_MEstadoReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MEstadoReservasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_MEstadoReservas);

        jMenuItem_MReservas.setText("De Reservas");
        jMenuItem_MReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MReservasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_MReservas);

        jMenuItem_MReversaActividades.setText("Reversa Actividades");
        jMenuItem_MReversaActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MReversaActividadesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_MReversaActividades);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuota.png"))); // NOI18N
        jMenu2.setText("Movimientos");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        jMenuItem11.setText("Cuota");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/procesamiento-por-lotes.png"))); // NOI18N
        jMenu3.setText("Procesos");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        jMenuItem12.setText("Generar Cobro");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("Reversar Cobro");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem14.setText("Actualiza Cuota");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuBar1.add(jMenu3);

        Consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consulta.png"))); // NOI18N
        Consultas.setText("Consultas");
        Consultas.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        CUsuario.setText("De Usuario");
        CUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUsuarioActionPerformed(evt);
            }
        });
        Consultas.add(CUsuario);

        CEntrenador.setText("De Entrenador");
        Consultas.add(CEntrenador);

        CLocalizacion.setText("De Localización");
        CLocalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLocalizacionActionPerformed(evt);
            }
        });
        Consultas.add(CLocalizacion);

        CSalas.setText("De Salas");
        CSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSalasActionPerformed(evt);
            }
        });
        Consultas.add(CSalas);

        CActividades.setText("De Actividades");
        CActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActividadesActionPerformed(evt);
            }
        });
        Consultas.add(CActividades);

        CHorarioActividaes.setText("De Horarios Actividades");
        CHorarioActividaes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHorarioActividaesActionPerformed(evt);
            }
        });
        Consultas.add(CHorarioActividaes);

        jMenuItem21.setText("De Cobro por Rango de Fecha");
        Consultas.add(jMenuItem21);

        jMenuItem22.setText("De Cobro por Cliente");
        Consultas.add(jMenuItem22);

        jMenuItem23.setText("De Cuota por Fecha");
        Consultas.add(jMenuItem23);

        jMenuItem24.setText("De Cuota por Clientes");
        Consultas.add(jMenuItem24);

        CClientes.setText("De Clientes");
        CClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CClientesActionPerformed(evt);
            }
        });
        Consultas.add(CClientes);

        jMenuItem26.setText("De Clientes con Balance pendiente");
        Consultas.add(jMenuItem26);

        jMenuBar1.add(Consultas);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        jMenu4.setText("Cerrar sesion");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenu4MouseReleased(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new GenerarCobro().setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem_MUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MUsuarioActionPerformed
        // TODO add your handling code here:
        new Usuario().setVisible(true);
    }//GEN-LAST:event_jMenuItem_MUsuarioActionPerformed

    private void CLocalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLocalizacionActionPerformed

    }//GEN-LAST:event_CLocalizacionActionPerformed

    private void jMenu4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseExited

    }//GEN-LAST:event_jMenu4MouseExited

    private void jMenu4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseReleased

    }//GEN-LAST:event_jMenu4MouseReleased

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MousePressed
        // TODO add your handling code here:
        setVisible(false);
        new InicioSesion().setVisible(true);
    }//GEN-LAST:event_jMenu4MousePressed

    private void MLocalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLocalizacionActionPerformed
        // TODO add your handling code here:
        new Localizacion().setVisible(true);
    }//GEN-LAST:event_MLocalizacionActionPerformed

    private void MSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSalasActionPerformed
        // TODO add your handling code here:
        new Salas().setVisible(true);
    }//GEN-LAST:event_MSalasActionPerformed

    private void jMenuItem_MActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MActividadesActionPerformed
        // TODO add your handling code here:
        new Actividades().setVisible(true);
    }//GEN-LAST:event_jMenuItem_MActividadesActionPerformed

    private void MEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEntrenadorActionPerformed
        // TODO add your handling code here:
        new Entrenador().setVisible(true);
    }//GEN-LAST:event_MEntrenadorActionPerformed

    private void jMenuItem_MEstadoReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MEstadoReservasActionPerformed
        // TODO add your handling code here:
        new EstadoReserva().setVisible(true);
    }//GEN-LAST:event_jMenuItem_MEstadoReservasActionPerformed

    private void jMenuItem_MClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MClientesActionPerformed
        // TODO add your handling code here:
        new Cliente().setVisible(true);
    }//GEN-LAST:event_jMenuItem_MClientesActionPerformed

    private void jMenuItem_MReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MReservasActionPerformed
        // TODO add your handling code here:
        new Reserva().setVisible(true);
    }//GEN-LAST:event_jMenuItem_MReservasActionPerformed

    private void jMenuItem_MReversaActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MReversaActividadesActionPerformed
        // TODO add your handling code here:
        new ReservaActividades().setVisible(true);
    }//GEN-LAST:event_jMenuItem_MReversaActividadesActionPerformed

    private void jMenuItem_MHorarioActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MHorarioActividadesActionPerformed
        // TODO add your handling code here:
        new HorarioActividades().setVisible(true);
    }//GEN-LAST:event_jMenuItem_MHorarioActividadesActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new Cuota().setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        new ReversarCobro().setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        new ActualizarCuota().setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void CUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUsuarioActionPerformed
        // TODO add your handling code here:
        new Consulta_Usuario().setVisible(true);
    }//GEN-LAST:event_CUsuarioActionPerformed

    private void CSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSalasActionPerformed
        // TODO add your handling code here:
        new Consulta_Salas().setVisible(true);
    }//GEN-LAST:event_CSalasActionPerformed

    private void CActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActividadesActionPerformed
        // TODO add your handling code here:
        new Consulta_Actividades().setVisible(true);
    }//GEN-LAST:event_CActividadesActionPerformed

    private void CHorarioActividaesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHorarioActividaesActionPerformed
        // TODO add your handling code here:
        new Consulta_Horario_Actividades().setVisible(true);
    }//GEN-LAST:event_CHorarioActividaesActionPerformed

    private void CClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CClientesActionPerformed
        // TODO add your handling code here:
        new Consulta_de_cliente().setVisible(true);
    }//GEN-LAST:event_CClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CActividades;
    private javax.swing.JMenuItem CClientes;
    private javax.swing.JMenuItem CEntrenador;
    private javax.swing.JMenuItem CHorarioActividaes;
    private javax.swing.JMenuItem CLocalizacion;
    private javax.swing.JMenuItem CSalas;
    private javax.swing.JMenuItem CUsuario;
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenuItem MEntrenador;
    private javax.swing.JMenuItem MLocalizacion;
    private javax.swing.JMenuItem MSalas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem_MActividades;
    private javax.swing.JMenuItem jMenuItem_MClientes;
    private javax.swing.JMenuItem jMenuItem_MEstadoReservas;
    private javax.swing.JMenuItem jMenuItem_MHorarioActividades;
    private javax.swing.JMenuItem jMenuItem_MReservas;
    private javax.swing.JMenuItem jMenuItem_MReversaActividades;
    private javax.swing.JMenuItem jMenuItem_MUsuario;
    // End of variables declaration//GEN-END:variables
}
